### PR TITLE
Update "version" string

### PR DESCRIPTION
**Pull request by tianon**
I updated the `version` string to `0.4.0-dev`, but I'm happy to modify if you'd rather it be something else (but I figured that now that `0.4.0` is out, `0.3.0` probably isn't the right value to be in there anymore :smile:).

### CODE REVIEW

**Comment by tianon** [comment]
It might also be prudent to update `app.Name` to `manifest-tool` (which I'm happy to roll in here or make a separate PR for if you agree). :+1:

**Comment by tianon** [comment]
If you wanted to get real crazy, `app.Name` could be set via `os.Args[0]`...  :innocent:

**Comment by tianon** [comment]
Some example output:
```console
$ manifest-tool --version
manifest-tool version 0.4.0-dev
$ ./manifest-tool --version
./manifest-tool version 0.4.0-dev
$ ~/docker/manifest-tool/manifest-tool --version
/home/tianon/docker/manifest-tool/manifest-tool version 0.4.0-dev
```

**Comment by estesp** [comment]
LGTM, thanks!

**Pull request merged**
