### PR TITLE
Add alpine base image

### PR DESCRIPTION
**Pull request by Starttoaster**
Closes https://github.com/estesp/manifest-tool/issues/165

### CODE REVIEW

**Comment by estesp** [comment]
Thanks for working on this! 

I have DCO check turned on for this repo, so if you can add a `Signed-off-by: First Lastname <you@email.com>` to your commit last line that would be great.

You also probably will need to rebase on the latest commit once I merge #167 as looks like some deps, versions, and go mod settings needed some love to get CI working properly.

**Comment by Starttoaster** [comment]
Thanks for the review @estesp !

Sorry about the DCO check! I was not on my normal dev machine when I committed that earlier. I've rebased, and re-committed with a signature.

**Comment by Starttoaster** [comment]
Woops! Since I'm on the right machine now, I also noticed PATH would not be set properly. Updated the Dockerfile.

**Comment by Starttoaster** [comment]
@estesp not trying to be a bother, but do you have more feedback on this? Aware you're busy and if this falls off your plate, that's understandable. Just wanted to make sure it didn't fall off your plate _on accident_, so to speak :)

**Comment by estesp** [comment]
Thanks for the reminder--I wasn't meaning to delay this long, but was getting a few other fixes squared away so I can do a point release and test your contribution of the new images.

**Review by estesp — APPROVED** [review]
LGTM

**Comment by estesp** [comment]
Working with the just-released v2.0.4 🎉 :
```
$ docker run -ti --entrypoint /bin/sh mplatform/manifest-tool:alpine
/ # manifest-tool -v
manifest-tool version 2.0.4 (commit: 0e4d8b32fec16134b7d0b7ea837af25cd10a1ed8)
/ #
```

**Pull request merged**
