### PR TITLE
Add support for mips64le

### PR DESCRIPTION
**Pull request by tianon**

### CODE REVIEW

**Comment by tianon** [comment]
FWIW, the including-`mips64le`-in-a-manifest side of this should already be covered by: https://github.com/estesp/manifest-tool/blob/7ec675a6f053fc4dff4c5bcb45b1a776e97aeafd/docker/util.go#L29

**Comment by tianon** [comment]
Blech:

```
# github.com/estesp/manifest-tool/vendor/github.com/docker/docker/pkg/system
vendor/github.com/docker/docker/pkg/system/stat_linux.go:11:3: cannot use s.Rdev (type uint32) as type uint64 in field value
```

**Comment by tianon** [comment]
Looks like we need https://github.com/moby/moby/pull/39646 / https://github.com/moby/moby/commit/5f0231bca193320e1a3d785a3ade0e64241fe580.

**Comment by estesp** [comment]
As soon as I verify #83 and merge, you should be able to rebase and get this working :)

**Comment by tianon** [comment]
Whoo, green! :smile:

**Pull request merged**
