### PR TITLE
Allow push to library/xxx via custom URL builder

### PR DESCRIPTION
**Pull request by estesp**
Fix the problem where library/xxx repos on DockerHub cannot be pushed to
because of name normalization in the reference package code.

This is solved by building custom URLs for manifest and blob upload
references when `library/` references are used and the hostname matches
the canonical DockerHub registry reference.

Signed-off-by: Phil Estes <estesp@gmail.com>

Fixes: #47

### CODE REVIEW

**Comment by estesp** [comment]
@tianon if you could test this when you get a chance.. obviously I don't have permissions on `library/` to do such testing :innocent:

**Comment by estesp** [comment]
I have tested non-`library/` manifest list creates and verify that code path is working properly with this PR

**Comment by tianon** [comment]
Yeah, let me pull this down real fast and try it out!

**Comment by tianon** [comment]
Looking good so far!
```
...
DEBU[0016] Manifest list push url: https://registry-1.docker.io/v2/library/irssi/manifests/latest 
...
```

Going to do a bit more testing to be 100% sure.

**Comment by tianon** [comment]
yep, both `image: library/irssi:latest` and `image: irssi:latest` work properly :metal:

**Comment by tianon** [comment]
For reference, my testing YAML was the following:
```yaml
---
image: library/irssi:latest
manifests:
  - image: amd64/irssi:latest
    platform:
      os: linux
      architecture: amd64
  - image: arm32v5/irssi:latest
    platform:
      os: linux
      architecture: arm
      variant: v5
  - image: arm32v7/irssi:latest
    platform:
      os: linux
      architecture: arm
      variant: v7
  - image: arm64v8/irssi:latest
    platform:
      os: linux
      architecture: arm64
      variant: v8
  - image: i386/irssi:latest
    platform:
      os: linux
      architecture: 386
  - image: ppc64le/irssi:latest
    platform:
      os: linux
      architecture: ppc64le
  - image: s390x/irssi:latest
    platform:
      os: linux
      architecture: s390x
```

**Comment by tianon** [comment]
Here's a bunch of the blob mount lines from `--debug`:
```
DEBU[0035] Mount of blob sha256:d090e79c8b6e0b3362cab798ee27aeb318f72383e2d3b6b184538ba4f2a78c22 succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:d090e79c8b6e0b3362cab798ee27aeb318f72383e2d3b6b184538ba4f2a78c22" 
DEBU[0036] Mount of blob sha256:f611f84acffe6a66fad3356eb9101ed9fff54e980701079bbce3ee4826ccd3ae succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:f611f84acffe6a66fad3356eb9101ed9fff54e980701079bbce3ee4826ccd3ae" 
DEBU[0036] Mount of blob sha256:aea5e5916c2c2e5ee21a45868654a7657e290124316b0102fe8bd1168157726d succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:aea5e5916c2c2e5ee21a45868654a7657e290124316b0102fe8bd1168157726d" 
DEBU[0037] Mount of blob sha256:0eb001c6294aa6446111dff9c41f55ac9db1cbb5a23f23688e03a5ad3a9a61fa succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:0eb001c6294aa6446111dff9c41f55ac9db1cbb5a23f23688e03a5ad3a9a61fa" 
DEBU[0038] Mount of blob sha256:7d1e5dc73154c8b6d49188d561f8a48afa624e118d79dc8d2dda9d672a6c93e4 succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:7d1e5dc73154c8b6d49188d561f8a48afa624e118d79dc8d2dda9d672a6c93e4" 
DEBU[0039] Mount of blob sha256:267d67fb143214dd38b8bf4e0450a9ebcebbbe9d1bf25c69842c27127057b46a succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:267d67fb143214dd38b8bf4e0450a9ebcebbbe9d1bf25c69842c27127057b46a" 
DEBU[0039] Mount of blob sha256:d4a5434e09b7ac8431060d347d6ef1233ae07514878fb2aff4085bcf441c29f3 succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:d4a5434e09b7ac8431060d347d6ef1233ae07514878fb2aff4085bcf441c29f3" 
DEBU[0040] Mount of blob sha256:b676e9b8213dc21a5ff4d2f5382386559bee357259e5032e9d72316ba5d17be7 succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:b676e9b8213dc21a5ff4d2f5382386559bee357259e5032e9d72316ba5d17be7" 
DEBU[0041] Mount of blob sha256:287a91c6a95cfe46f948ffd5a719ed21b8fe09bbfaa555fe0ee169527d815eae succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:287a91c6a95cfe46f948ffd5a719ed21b8fe09bbfaa555fe0ee169527d815eae" 
DEBU[0042] Mount of blob sha256:7a24ae4c938737866051a97c325121a3f37fe1c6459e7b289f96ba5dc219cfd2 succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:7a24ae4c938737866051a97c325121a3f37fe1c6459e7b289f96ba5dc219cfd2" 
DEBU[0042] Mount of blob sha256:e02758d4c956f8d504e31e114eceb48a8af038537f73916e5ac68c5f0657147e succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:e02758d4c956f8d504e31e114eceb48a8af038537f73916e5ac68c5f0657147e" 
DEBU[0043] Mount of blob sha256:5f39dbffcd07e3254246d3c2e4b3532c3697ed04f83eadf5433da820098787df succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:5f39dbffcd07e3254246d3c2e4b3532c3697ed04f83eadf5433da820098787df" 
DEBU[0049] Mount of blob sha256:b9eafb3802fb5850da75355184a0e22a0fb13d51f6c1cf1c8bfa8b95f50b3a1b succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:b9eafb3802fb5850da75355184a0e22a0fb13d51f6c1cf1c8bfa8b95f50b3a1b" 
DEBU[0050] Mount of blob sha256:703e0009ec36e4a53d6f2c9c4bf6bace2564dd722d8e531fb2891b413fe5e2c7 succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:703e0009ec36e4a53d6f2c9c4bf6bace2564dd722d8e531fb2891b413fe5e2c7" 
DEBU[0051] Mount of blob sha256:81191a41e6bb93b8d8f0d0093574b435a5a10b291a00840f4330f9b44b35f42e succeeded, location: "https://registry-1.docker.io/v2/library/irssi/blobs/sha256:81191a41e6bb93b8d8f0d0093574b435a5a10b291a00840f4330f9b44b35f42e" 
```

**Comment by estesp** [comment]
Thanks for the testing @tianon! Looks good

**Pull request merged**
