### PR TITLE
Automatically populate OS and architecture from source manifests (if unspecified)

### PR DESCRIPTION
**Pull request by tianon**
Finally implemented that TODO item in the README (since looking at the code, it seemed relatively simple to plug in to the existing "inspect" logic at push-time).

### CODE REVIEW

**Comment by tianon** [comment]
In testing this, I created [`tianon/test:multiarch`](https://hub.docker.com/r/tianon/test/tags/) from the following YAML:
```yaml
image: tianon/test:multiarch
manifests:
  - image: busybox:latest
  - image: i386/busybox:latest
  - image: s390x/busybox:latest
  - image: ppc64le/busybox:latest
  - image: aarch64/busybox:latest
  - image: armhf/busybox:latest
  - image: armel/busybox:latest
```
```console
$ ./manifest-tool inspect tianon/test:multiarch
Name:   tianon/test:multiarch (Type: application/vnd.docker.distribution.manifest.list.v2+json)
Digest: sha256:2247a1ae4bade99060e4cf1c7f59642a6c6510a4a7224289e67d6e9d6e4abc19
 * Contains 7 manifest references:
1    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
1       Digest: sha256:817a12c32a39bbe394944ba49de563e085f1d3c5266eb8e9723256bc4448680e
1  Mfst Length: 527
1     Platform:
1           -      OS: linux
1           -    Arch: amd64
1           - Variant: 
1           - Feature: 
1     # Layers: 1
         layer 1: digest = sha256:4b0bc1c4050b03c95ef2a8e36e25feac42fd31283e8c30b3ee5df6b043155d3c

2    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
2       Digest: sha256:284dc62e6405bd5ab717e91bc04b7738bc72bdefdaebc3fdde6153a8195440f1
2  Mfst Length: 506
2     Platform:
2           -      OS: linux
2           -    Arch: amd64
2           - Variant: 
2           - Feature: 
2     # Layers: 1
         layer 1: digest = sha256:a1e7dc85386c60bcc251f87ee5b8d371f081189110617e8dca2ee475f4b34200

3    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
3       Digest: sha256:ad90fd24845e15233a89713c1918c8a21a36059166a9996e66fde9bb3ed299e3
3  Mfst Length: 528
3     Platform:
3           -      OS: linux
3           -    Arch: s390x
3           - Variant: 
3           - Feature: 
3     # Layers: 1
         layer 1: digest = sha256:fcc9f2920de17785a5a79650eec9d470760b7c581ee3bad358281d9c869d0582

4    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
4       Digest: sha256:7f526ef3b2095f7eef2da847428a35414f7dda993b49d749d11c89e1522a1eb7
4  Mfst Length: 528
4     Platform:
4           -      OS: linux
4           -    Arch: ppc64le
4           - Variant: 
4           - Feature: 
4     # Layers: 1
         layer 1: digest = sha256:6c6d0c1f564694e4a3c534d2f6d9ce94359239a8d64b3a6dbc17b7db3f04ecd0

5    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
5       Digest: sha256:8f461e29575fe0ea3694c3a4e120be7112d50ad4d9fab29931f973d5e06f4abc
5  Mfst Length: 528
5     Platform:
5           -      OS: linux
5           -    Arch: arm64
5           - Variant: 
5           - Feature: 
5     # Layers: 1
         layer 1: digest = sha256:ac76427ebb1a69cf09bb3fdc4e28a808024e0a582643638ab5db595c78880806

6    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
6       Digest: sha256:35f3b1eaf6db413c52b43d7f88e836fbeb0ffa38bf12da5835db95d8248c5c39
6  Mfst Length: 528
6     Platform:
6           -      OS: linux
6           -    Arch: arm64
6           - Variant: 
6           - Feature: 
6     # Layers: 1
         layer 1: digest = sha256:40a6abee9428d7e61be3ed5c37716c06e7eb6d7b583d42745b1c7831064cbcd0

7    Mfst Type: application/vnd.docker.distribution.manifest.v2+json
7       Digest: sha256:428a04a2357ddd276038b061666bfd516d8cf0bb4ac86dde6475f9cbbfe49e5f
7  Mfst Length: 528
7     Platform:
7           -      OS: linux
7           -    Arch: arm64
7           - Variant: 
7           - Feature: 
7     # Layers: 1
         layer 1: digest = sha256:15f777a55c7e53f05e44421c736ba68ed3b9f7a43b2a5984aff747ffc425882c

```

**Comment by tianon** [comment]
Not sure what to do about variants and features (the other parts of the `Platform` struct), since I'm not sure individual images even _can_ have those properties right now.

**Comment by estesp** [comment]
They can have `variant` and `feature` entries; the problem is that the Docker engine is not enabled to use those fields to make image resolution decisions. Need someone to lead the charge there, and most likely will be someone who has opinions on how embedded platforms should be represented (e.g. the ARM community). I haven't had much luck with Linaro involvement other than some initial discussions last year at DockerCon.

As far as this PR in general, it looks like auto-resolution left you with an image that isn't quite as useful because underlying image configs don't necessarily represent the target properly? Of course you and I already discussed this issue, and it is more of a build-time/cross-build issue that needs to be solved for auto-generation to be correct.

**Comment by tianon** [comment]
Well, yes and no -- the auto-resolution did leave something to be desired, but only in the edge cases we've already discussed (ie, building 32bit images on a 64bit host, or building armv7/armv5 images on an armv8 64bit host).  For cases where I wasn't doing any kind of cross-building, it worked exactly the way I expected it to and gave me exactly the metadata I was looking for (`linux/amd64`, `linux/s390x`, `linux/ppc64le`, `windows/amd64`).

IMO, the auto-resolution is still a useful feature to have, especially for folks who aren't doing cross-building like I am, and even more especially if Docker/OCI might eventually support a full `platform` struct on an individual image manifest.

**Pull request merged**
