### PR TITLE
Add windows/arm to the validOSArch map

### LINKED ISSUE #59: manifest-tool doesn't support arm on windows

### PR DESCRIPTION
**Pull request by JoshEbersol**
Fixes #59.

### CODE REVIEW

**Comment by tianon** [comment]
Is this really ARM 32bit? Or is this v8 and 64bit? (and thus `windows/arm64`)

**Comment by StefanScherer** [comment]
@tianon Good catch.
It seems to be arm, the `mcr.microsoft.com/windows/nanoserver:1809` has a manifest list with windows/amd64 and windows/arm, but I don't know if the binaries in the image are for 32bit or 64bit, so it may be wrong there, too.

**Comment by estesp** [comment]
Based on the CL in Go, with updates in [this issue](https://github.com/golang/go/issues/26148), the string is "arm" because they only added 32-bit support. Checking out `golang/go` runtime dir seems to confirm this is actually `arm`, not `arm64`, and [only supports `GOARM=7`](https://github.com/golang/go/blob/master/src/runtime/os_windows_arm.go#L13-L17).

Unless someone finds something different, I will probably go ahead and accept this PR.

**Comment by JoshEbersol** [comment]
Yes, 32-bit arm was my intent here.  Thanks for double checking!

**Pull request merged**
