### PR TITLE
move PushManifestList and all its utils into pkg

### PR DESCRIPTION
**Pull request by deitch**
Fundamentally, moves `pushManifestList()` into `pkg/registry.PushManifestList()` so it is useful as a library API.

Also removes any of the command-line `cli.Context` references from within `PushManifestList` so it stays cli-neutral, and keeps those in the root cmd area.

En passant, has to move a few utilities around.

### CODE REVIEW

**Comment by deitch** [comment]
As discussed with @estesp

**Comment by deitch** [comment]
Checking in on this one @estesp ?

**Comment by estesp** [comment]
Hey @deitch; sorry for the delay. Had a really busy week, but will try and take a deeper look at this later.

**Comment by deitch** [comment]
Nothing like post-Thanksgiving, eh? 😀

I will look forward to it.

**Review by estesp — APPROVED** [review]
LGTM. This seems like a reasonable way to make it reusable via API.

**Pull request merged**
