### PR TITLE
Updates to this project for use with Kubernetes, Weave and others

### PR DESCRIPTION
**Pull request by luxas**
Hi, I know this project is just a workaround etc. but I'm gonna implement manifest lists now for Kubernetes and eventually Weave. 

I went through the source code today and hacked on things I saw I could improve, and here's the result.
Especially, I don't want to have to create a spec file every time I have to make a manifest list.

The pattern I'm gonna implement is to push single manifest images for every arch to `registry/binary-arch:version` and then run 
```shell
# set ${registry},${binary}, ${version} before
./manifest-tool push from-args \
  --platforms linux/amd64,linux/arm,linux/arm64 \
  --template ${registry}/${binary}-ARCH:${version} \
  --target ${registry}/${binary}:${version}
```

I also fixed lint, vet, test failures etc.

I'm gonna release v0.3.0 myself now in my fork, but putting this here, and if you want it, feel free to merge and release a more official version yourself :smile:
cc @estesp

### CODE REVIEW

**Comment by estesp** [comment]
@luxas thanks for this! This project **is** somewhat of a stopgap, but I'm happy to have some cleanups as I know others are using it for the short term. I will look this over and most likely bring it in as a new version and make a "real" release.

**Comment by StefanScherer** [comment]
@luxas Thanks for providing a binary.
The current work seems to be in https://github.com/docker/docker/pull/27455

**Comment by StefanScherer** [comment]
Thanks @luxas your binary makes it really very easy to deploy multiarch images.
I just have synced my AppVeyor + Travis build for winspector to build a manifest for released version + new latest in just a [few lines of bash in deploy.sh](https://github.com/StefanScherer/winspector/blob/111060c91fb9cf09a4a57be8c66baddee4ed79fb/deploy.sh#L17-L32) on Travis.

**Comment by luxas** [comment]
Yeah, I'm subscribed to the thread and am excitedly waiting for official support.
In the meantime I'm busy fixing so it actually works for k8s, weave and others short-term, so that's why I made this ('cause no one actually wants to make spec files, although they are much more powerful :smile:)

@StefanScherer Glad to hear you've adopted it!

@estesp Indeed, it's a stopgap, but anyway, I need it _now_ :)
Can you merge this and I'll fix things in a follow up if there's need to?

**Pull request merged**
